# Generated by Django 4.1 on 2023-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_picture_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name': '住所', 'verbose_name_plural': '住所一覧'},
        ),
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(choices=[('池田市', '池田市'), ('泉大津市', '泉大津市'), ('泉佐野市', '泉佐野市'), ('和泉市', '和泉市'), ('茨木市', '茨木市'), ('大阪狭山市', '大阪狭山市'), ('大阪市', '大阪市'), ('貝塚市', '貝塚市'), ('柏原市', '柏原市'), ('交野市', '交野市'), ('河南町', '河南町'), ('河内長野市', '河内長野市'), ('岸和田市', '岸和田市'), ('熊取町', '熊取町'), ('堺市', '堺市'), ('四條畷市', '四條畷市'), ('島本町', '島本町'), ('吹田市', '吹田市'), ('摂津市', '摂津市'), ('泉南市', '泉南市'), ('太子町', '太子町'), ('大東市', '大東市'), ('高石市', '高石市'), ('高槻市', '高槻市'), ('田尻町', '田尻町'), ('忠岡町', '忠岡町'), ('千早赤阪村', '千早赤阪村'), ('豊中市', '豊中市'), ('豊能町', '豊能町'), ('富田林市', '富田林市'), ('寝屋川市', '寝屋川市'), ('能勢町', '能勢町'), ('羽曳野市', '羽曳野市'), ('阪南市', '阪南市'), ('東大阪市', '東大阪市'), ('枚方市', '枚方市'), ('藤井寺市', '藤井寺市'), ('松原市', '松原市'), ('岬町', '岬町'), ('箕面市', '箕面市'), ('守口市', '守口市'), ('八尾市', '八尾市')], max_length=10),
        ),
    ]
