# Generated by Django 4.1 on 2023-09-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_addresses_options_alter_addresses_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='user_picture/noname_user.png', null=True, upload_to='user_picture/'),
        ),
    ]
