# Generated by Django 4.1 on 2023-09-27 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('家具', '家具'), ('家電', '家電'), ('自転車', '自転車'), ('楽器', '楽器'), ('生活雑貨', '生活雑貨'), ('子供用品', '子供用品'), ('ホビー、ゲーム', 'ホビー、ゲーム'), ('服/ファッション', '服/ファッション'), ('靴/バック', '靴/バック'), ('コスメ/ヘルスケア', 'コスメ/ヘルスケア'), ('食品', '食品'), ('スポーツ', 'スポーツ'), ('その他', 'その他')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_items', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '出品',
                'verbose_name_plural': '出品一覧',
            },
        ),
        migrations.CreateModel(
            name='ItemPictures',
            fields=[
                ('item_picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='item_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '出品写真',
                'verbose_name_plural': '出品写真一覧',
            },
        ),
    ]
